#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="GIT"
export CC="xlclang"
export CXX="xlclang++"
export CFLAGS="-std=gnu11 -qnocsect"
export CXXFLAGS="-+ -qnocsect"
if [ "${ZOPEN_INSTALL_DIR}x" = "x" ]; then
  export ZOPEN_INSTALL_DIR="${HOME}/zot/prod/CMake"
fi
export ZOPEN_BOOTSTRAP_OPTS="--prefix=${ZOPEN_INSTALL_DIR} -- -DCMAKE_BUILD_TYPE=Release"
export ZOPEN_CONFIGURE="skip"
export ZOPEN_CHECK="skip"

export ZOPEN_GIT_URL="https://github.com/Kitware/CMake.git"
export ZOPEN_GIT_DEPS="git make"
export ZOPEN_GIT_TAG="v3.18.0"

zopen_check_results()
{
  return 3 # non-functional
}

