#!/bin/sh
mydir=$(cd $(dirname $0) && echo $PWD)
export CC=xlclang

export PATH="${mydir}":"${mydir}/../CMake/bin":${PATH}
rm -rf build
mkdir -p build
cd build
cmake --trace -D CMAKE_C_COMPILER=${CC} -G Ninja .. && ninja
