#!/bin/sh
mydir=$(cd $(dirname $0) && echo $PWD)
export CC=clang
#export CFLAGS="-I${mydir}/include"
export CMAKE=cmake
export NINJA=ninja

if ! ${CC} --version ; then
  echo "Unable to find ${CC} compiler" >&2
  exit 4
fi
if ! ${CMAKE} --version ; then
  echo "Unable to find ${CMAKE}" >&2
  exit 4
fi
if ! ${NINJA} --version ; then
  echo "Unable to find ${NINJA}" >&2
  exit 4
fi

#
# Delete the old 'build' tools and start from scratch
#
rm -rf build
mkdir -p build
cd build

cmake -D CMAKE_C_COMPILER=${CC} -G Ninja .. 
